name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-
      
      #      - name: Install Unity
      #        uses: game-ci/unity-builder@v4
      #        with:
      #          version: '2022.3.18f1'
      #            
      #      # xvfb-run のインストール
      #      - name: Install xvfb
      #        run: sudo apt-get install -y xvfb

      - uses: game-ci/unity-builder@v4
        with:
          unityVersion: auto
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ${{ runner.temp }}/qodana/results